### ISSUE TITLE
Create a rich README.md and CONTRIBUTION.md

### ISSUE THREAD

**Issue by shamahdev** [Shaddamah/gsuite-desktop-client#1]
I'm not good at creating a README.md so if anyone want to do it please comment and i'll Assign you, here's the description about this project

---
Unofficial Google Suite Desktop Client made with Electron. Other web apps like Trello and Airtable have their on desktop versions of the app with Electron, Since google doesn't have it, i decided to create it myself.

How to run the project:
```
npm install
npm start
```

**Comment by munawariz** [comment]
I would like to clear this issue. Please assigned it to me

**Comment by shamahdev** [comment]
Sure, it's still free! Go ahead.
